### ISSUE TITLE
Ability to check if a file is in the cache

### ISSUE THREAD

**Issue by daaku** [tj/haml.js#12]
Since the cache is currently not exposed, the caller has to keep track of which files are cached, which essentially means it needs to maintain a copy of the list of keys in the internal cache. It would be useful to expose `cache.hasOwnProperty()` to allow checking for this in the internal cache itself.

**Comment by daaku** [comment]
Another issue I ran into is the ability to warm up the cache. I'm trying to implement some basic partial support and would be great to have the ability to say "cache this, but don't render anything".

**Comment by tj** [comment]
We do this within Express, we just read all the partials into memory, IMO this should not be a feature of a specific template engine. I will expose the cache object though, so you could just do a quick readdir and chuck the contents in there

**Comment by tj** [comment]
Exposing Haml compilation cache. Closed by 3309a64129b80f5c7907d1c78a91e3624c8ae683

**Comment by daaku** [comment]
Thanks TJ
