### ISSUE TITLE
Add support for IE conditional comments

### ISSUE THREAD

**Issue by ciaranj** [tj/haml.js#13]
Those of us stuck supporting IE often need to put in conditional comments, the 'old' haml engine that shipped with express supported this, the new one doesn't currently :( 

Patch to follow.

**Comment by ciaranj** [comment]
Test and patch here: http://github.com/ciaranj/haml.js/commit/7d6d4b5d2c614a25381ba70aaa9fed1ff72988a8

**Comment by tj** [comment]
merged

**Comment by ciaranj** [comment]
cheers
