### ISSUE TITLE
Handle undefined variables

### ISSUE THREAD

**Issue by Burgestrand** [tj/haml.js#21]
The following code generates an error (undefined variable):

```
%tag= undefined_variable || 'default value'
```

**Comment by tj** [comment]
if its not declared then theres not much i can do about it, thats the nature of js

**Comment by Burgestrand** [comment]
Yargh, this is why you don't file bug reports at 00 AM. :)

**Comment by tj** [comment]
:D

**Comment by tj** [comment]
if you pass { locals: { something: undefined }} and do something || 'default value' it SHOULD work (I think), I would imagine `with()` still adds that member to the scope

**Comment by Burgestrand** [comment]
Yes it does :)
