### ISSUE TITLE
blank line confuses indentation

### ISSUE THREAD

**Issue by weepy** [tj/haml.js#26]
Could be same as previous problem. 

<pre>
#rhs
  %h4#score
  #words
  #incorrect

.clear
</pre>

Gives

<pre>
&lt;div id="rhs">
&lt;h4 id="score">&lt;/h4>

&lt;div id="words">&lt;/div>

&lt;div id="incorrect">&lt;/div>

&lt;div class="clear">&lt;/div>
</pre>

Note that #rhs div is not closed as expected.

**Comment by tj** [comment]
gah! lol there is some deeper issue in there im not seeing... hmm,
i will spec these and try to figure out whats wrong
