### ISSUE TITLE
Please expose Parser as a public symbol.

### ISSUE THREAD

**Issue by tyrda01** [tj/haml.js#32]
Hi, 

We want to use haml.js to write client side JavaScript which is returned on demand. i.e. make a request to express for "/foo/view.chaml' -> get back the javascript for the corresponding haml template, which we can now use client side to generate the HTML for various AJAX calls. 

The only change required to make this happen for haml.js is that Parser is exposed in the exports.

Thanks,

Dave

**Comment by thisivan** [comment]
I'm doing this with the current version:

``` javascript
return new Parser('%h1 haml code').js;
```

**Comment by saschagehlich** [comment]
https://github.com/visionmedia/haml.js/blob/17f90754c2782cb435bb824be698ffdbc062d08a/lib/haml.js#L282
