### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by tj** [tj/haml.js#4]
provide parser context, as well as come up
with a little hack to support filenames

**Comment by daaku** [comment]
+1 -- this would be awesome

**Comment by frank06** [comment]
I'm getting

```
SyntaxError: (Haml):11 unexpected indent
    at <error: SyntaxError: unexpected indent>
    at <error: SyntaxError: unexpected indent>
    at [object Object].<anonymous> (/Users/ftreacy/.kiwi/current/seeds/haml/0.1.0/lib/haml.js:600:21)
```

 I cannot find the offending 'unexpected indent'...i'm manually re-indenting with spaces (i guess) lines 11..(?)  and it's driving me crazy@!  This worked fine with (creationix's) haml-js

Any hint? :)

**Comment by ciaranj** [comment]
Might stand a better chance with your template ? :)

**Comment by tj** [comment]
post a gist of your template. haml-js was more or less a regexp hack not really a "true" parser, so in some cases mine will be less lenient (at the moment)

**Comment by frank06** [comment]
Sure :) well turns out i just found the problem.

I make textmate remove traling whitespace, so when i have an empty line between pieces of haml, the parser doesn't like that. The solution for now is to remove all those `\n`s, but this worked fine with haml-js.  Do you think it's fair to open a ticket for this?

**Comment by ciaranj** [comment]
Actually this keeps biting me too,  esp. when I 'vim' my templates remotely, I'm happy to submit a patch.

**Comment by frank06** [comment]
(i mean would it be feasible to ignore the indentation level of empty lines?)

**Comment by frank06** [comment]
thanks!

**Comment by ciaranj** [comment]
hmm, actually my issue wasn't on empty lines, more the _last_ line, I'm sure I've some examples where there's empty lines..but they probably dont' have whitespace on them.

**Comment by tj** [comment]
ya we should probably open an issue for that. I have newlines being ignored
in a couple contexts but there is probably a bug there

**Comment by tj** [comment]
as far as parsing goes its best not to, since it could be interpreted as an indent,
but in this case if its on the same indentation level we could just ignore those.

**Comment by xdamman** [comment]
When would this be implemented? Debugging a haml is awful at the moment.
How do you do? Any tip?

Also, how do you give variables to a partial? !=this.partial('file',{var1:x,var2:y})  ?
Cannot make it work but it might come from somewhere else, but it's so difficult to find out without a proper debugger.

Thanks
