### ISSUE TITLE
HAML.js + Express 3

### ISSUE THREAD

**Issue by the-teacher** [tj/haml.js#48]
https://github.com/visionmedia/haml.js/

``` javascript
 app.register('.haml', require('hamljs'));
```

but express 3.0.0alpha1 / 2012-04-15  cange log say:

```
* Removed `app.register()`
```

What should I do?

**Comment by tj** [comment]
`app.engine()` is similar but has a slightly different interface, `app.engine('.haml', hamljs.renderFile)`

**Comment by the-teacher** [comment]
> node

``` javascript
haml = require('hamljs')
haml.renderFile => ''undefined'

haml.render('%h1 hello world')
'\n<h1>hello world</h1>'
```

> node app.js

``` javascript
var app, express, http, routes, server;

express = require('express');

routes = require('./routes');

http = require('http');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');

  app.set('view engine', 'haml');
  app.engine('.haml', require('hamljs').render;

app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(express["static"](__dirname + '/public'));
});

```

gives

**if ('function' != typeof fn) throw new Error('callback function required');
                                     ^
Error: callback function required**

Sorry, I'm just beginner for node.js.Can you help me to use HAML as default engine?

There is my  test Repo

https://github.com/the-teacher/ExpressOnSteroids

**Comment by eldavido** [comment]
I'm also seeing this, will take a look if I can't get it figured out later

**Comment by the-teacher** [comment]
Hello, but it's work fine with **require 'consolidate'**.

https://github.com/the-teacher/ExpressOnSteroids/blob/master/src/app.coffee#L15
