### ISSUE TITLE
HAML.js + Express 3 (reopen)

### ISSUE THREAD

**Issue by the-teacher** [tj/haml.js#49]
Sorry I can't reopen this https://github.com/visionmedia/haml.js/issues/48
I think, I should to open new issue

> node

``` javascript
haml = require('hamljs')
haml.renderFile => ''undefined'

haml.render('%h1 hello world')
'\n<h1>hello world</h1>'
```

> node app.js

``` javascript
var app, express, http, routes, server;

express = require('express');

routes = require('./routes');

http = require('http');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');

  app.set('view engine', 'haml');
  app.engine('.haml', require('hamljs').render;

app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(express["static"](__dirname + '/public'));
});

```

gives

**if ('function' != typeof fn) throw new Error('callback function required');
                                     ^
Error: callback function required**

Sorry, I'm just beginner for node.js.

**Can you help me to use HAML as default engine?**

There is my  test Repo

https://github.com/the-teacher/ExpressOnSteroids

**Comment by tj** [comment]
ah, yeah i thought we had a renderFile. you could always use consolidate.js, it has hamljs

**Comment by the-teacher** [comment]
Thank you, I will try

**Comment by the-teacher** [comment]
It's work!

Great! Now my first Express-application finished! Now I can study Node.js technology with my favorite tools CoffeeScript, Sass, Haml.

Thank you very much!

https://github.com/the-teacher/ExpressOnSteroids

**Comment by stewartmatheson** [comment]
Hello, 

Not totally sure what the outcome is here as i am getting the same issue.  Could you please expand on how you fixed this and the state of code

**Comment by the-teacher** [comment]
Hello! I love haml, but I think Haml is not best solution for Node.js -- Jade is better.
Yes, I started with Haml - it's work good. Do you really want to use Haml?

**Comment by the-teacher** [comment]
You can turn on it with this strings

https://github.com/the-teacher/ExpressOnSteroids/blob/master/src/app.coffee#L14

**Comment by stewartmatheson** [comment]
@the-teacher Your right Jade is much better supported. I did not understand that when I posted this message but thanks for your reply. There is almost no difference between the two as well so yes looks like I will be going with Jade.

**Comment by tj** [comment]
yeah on the outside they are very similar, internally jade is a lot more robust now
