### ISSUE TITLE
underscore should be allowed for id/class

### ISSUE THREAD

**Issue by daaku** [tj/haml.js#5]
class: /^.([a-zA-Z0-9-_]+)/,
  id: /^#([a-zA-Z0-9-_]+)/,

**Comment by tj** [comment]
I will change it to just be:
    [\w-]+

missed this though thanks :)

**Comment by tj** [comment]
Fixed ids and classes allowing underscores. Closed by 94fb8cf18e0ded2b7231063ad0ad4c173b5ab422
