### ISSUE TITLE
String interpolation doesn't work

### ISSUE THREAD

**Issue by pawelkomarnicki** [tj/haml.js#61]
I don't know why, but when installed with expressjs the string interpolation doesn't work at all, it just outputs the text

**Comment by saschagehlich** [comment]
String interpolation was not available with 0.6.1 (the current version on npm). I just published 0.6.2 - try again with that one.

**Comment by pawelkomarnicki** [comment]
Works for normal tags, but doesn't still work for :javascript or inside %script

**Comment by pawelkomarnicki** [comment]
Also doesn't work for stuff like:

```
%td
  %i.fa.fa-money
  Money reports #{ some_variable }
```

But works when "Money reports" are wrapped in a %span tag
