### ISSUE TITLE
data-* attribute support?

### ISSUE THREAD

**Issue by jakelazaroff** [tj/haml.js#62]
Does this implementation support data-\* attributes? According to the official spec, I should be able to use the key `data` with another hash (http://haml.info/docs/yardoc/file.REFERENCE.html#html5_custom_data_attributes).

When I try to do that with this library (via consolidate) though, I get this error:
`SyntaxError: (/Users/jake/Sites/test/src/index.haml): Unexpected token ] at Function (<anonymous>) at /Users/jake/Sites/test/node_modules/hamljs/lib/haml.js:662:14 at Object.HAML.render (/Users/jake/Sites/test/node_modules/hamljs/lib/haml.js:676:6) at Function.exports.haml.render (/Users/jake/Sites/test/node_modules/consolidate/lib/consolidate.js:389:21) at /Users/jake/Sites/test/node_modules/consolidate/lib/consolidate.js:146:25 at /Users/jake/Sites/test/node_modules/consolidate/lib/consolidate.js:99:5 at fs.js:266:14 at Object.oncomplete (fs.js:107:15)`

My HAML file is pretty simple (and it renders fine when I remove the nested hash from the script tag):

``` haml
!!! 5
%html

  %head
    %title Test

    / javascript 
    %script{ src: "/assets/scripts/vendor/require/require-2.1.10.js", data: { main: "/assets/scripts/modules/application" }}

  %body
```

My app.js:

``` javascript
var express = require('express');

var app = express();

app.set('view engine', 'haml');
app.set('views', __dirname + '/src');

app.engine('.haml', require('consolidate').haml);

app.get('/', function (req, res) {
    res.render('index');
});

app.listen(4000);
```

**Comment by saschagehlich** [comment]
Related: https://github.com/visionmedia/haml.js/issues/34

I hope to find some time for this later this week. The problem is that I'll have to rewrite quite a lot of code for this.

**Comment by paazmaya** [comment]
Perhaps the `attrs()` method at https://github.com/tj/haml.js/blob/master/lib/haml.js#L305 should be extended to handle `data` separately.
Should there also be a `data` getter?
