### ISSUE TITLE
Does not work with Express 3 without Consolidate.js

### ISSUE THREAD

**Issue by eddiezane** [tj/haml.js#63]
Because Express 3 expects the engine function to be `(path, options, callback)` and the current state of renderFile includes encoding as a parameter, the example in the README.md will not work.

The only way to use hamjs with Express 3 right now is to use Consolidate.js.

Suggestions:
  Drop encoding as a parameter to renderFile to match similar behavior of ejs or jade.

  State in README.md that hamljs will only work with Express when using Consolidate.

**Comment by kaworu** [comment]
Please this should be adressed, I've just lost two hours trying to understand why I could not use locals variables :(

**Comment by cellis** [comment]
bump

**Comment by slowpoison** [comment]
:+1: 
Still not fixed :disappointed:

**Comment by soyuka** [comment]
With express4 I'm using:

```
app.engine('.haml', function(str, options, fn) {
  options.locals = util._extend({}, options)
  return hamljs.renderFile(str, 'utf-8', options, fn)
})
```

**Comment by jhamon** [comment]
I ended up doing the same @soyuka . It's a simple workaround, but as a newcomer to node and express, it took me quite a bit of headscratching to find this solution.

**Comment by robincsamuel** [comment]
Thanks @soyuka :)
