### ISSUE TITLE
Add :css filter

### ISSUE THREAD

**Issue by tj** [tj/haml.js#7]
as shortcut for
    <style type="text/css">

**Comment by gf3** [comment]
Meh. Why promote inline styles?

**Comment by tj** [comment]
its nice sometimes for quick shit, just
like promoting inline js, there are times and places :)

**Comment by gf3** [comment]
You make it too easy, TJ. You're an enabler! ;-)

**Comment by tj** [comment]
:D haha. if its not in the spec I will leave it out, cant remember now actually

**Comment by ciaranj** [comment]
I don't think its in the spec, but :sass is ?

**Comment by gf3** [comment]
Odd.

**Comment by tj** [comment]
Actually, now that I think about it this might be nice,
because otherwise you would have to do something like:
    %style{ type: 'text/css' }
       :plain
          .....

**Comment by tj** [comment]
but like gf3 said the use-case for this is probably pretty small
