### ISSUE TITLE
Add filter for server side javascript

### ISSUE THREAD

**Issue by ryankuykendall** [tj/haml.js#9]
The :javascript filter outputs a <script> tag to the HTML source...there should be a filter for doing larger blocks of javascript server side like this:

:server_side_javascript

This would essentially be the equivalent of the following filter as used in Ruby frameworks:

:ruby

**Comment by tj** [comment]
so its just a block of js that gets executed? more or less
the same as:
    - doWhatever()

? I never used :ruby, probably because its a bad idea to have large chunks of code in
your view
